<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.nexus</groupId>
        <artifactId>nexus-common</artifactId>
        <version>${nexus-version}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>nexus-common-mybatis-plus</artifactId>
    <description>nexus-common-mybatis-plus mybatis-plus通用依赖项</description>
    <packaging>jar</packaging>

    <dependencies>

        <!-- nexus-common-core 核心依赖 -->
        <dependency>
            <groupId>com.nexus</groupId>
            <artifactId>nexus-common-core</artifactId>
        </dependency>

        <!-- 数据库驱动 -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
            <version>${mysql-connector.version}</version>
        </dependency>

        <!-- 数据库连接池 druid-->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-3-starter</artifactId>
        </dependency>

        <!-- MyBatis-Plus启动器 -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <!-- MyBatis-Plus 分页插件 -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-jsqlparser-4.9</artifactId>
        </dependency>
    </dependencies>
</project>
