<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.nexus</groupId>
        <artifactId>nexus-common</artifactId>
        <version>${nexus-version}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>nexus-common-shiro</artifactId>
    <description>nexus-common-shiro 通用 shiro 依赖项</description>
    <packaging>jar</packaging>

    <dependencies>

        <!-- nexus-common-core 核心通用依赖 -->
        <dependency>
            <groupId>com.nexus</groupId>
            <artifactId>nexus-common-core</artifactId>
        </dependency>

        <!-- nexus-common-token token 通用依赖 -->
        <dependency>
            <groupId>com.nexus</groupId>
            <artifactId>nexus-common-token</artifactId>
        </dependency>

        <!-- shiro 整合SpringBoot依赖 -->
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-spring-boot-web-starter</artifactId>
            <classifier>jakarta</classifier>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.shiro</groupId>
                    <artifactId>shiro-crypto-cipher</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.shiro</groupId>
                    <artifactId>shiro-crypto-hash</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.shiro</groupId>
                    <artifactId>shiro-web</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.shiro</groupId>
                    <artifactId>shiro-spring</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-web</artifactId>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-spring</artifactId>
            <classifier>jakarta</classifier>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.shiro</groupId>
                    <artifactId>shiro-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- shiro 和 ehcache(缓存管理器) -->
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-ehcache</artifactId>
        </dependency>
    </dependencies>
</project>
