<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.nexus</groupId>
        <artifactId>nexus-common</artifactId>
        <version>${nexus-version}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>nexus-common-doc</artifactId>
    <description>nexus-common-doc 接口文档通用依赖项</description>
    <packaging>jar</packaging>

    <dependencies>

        <!-- nexus-common-core 核心依赖 -->
        <dependency>
            <groupId>com.nexus</groupId>
            <artifactId>nexus-common-core</artifactId>
        </dependency>

        <!-- Swagger 接口文档-->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <!-- knife4j 接口文档-->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>
