<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.nexus</groupId>
        <artifactId>nexus</artifactId>
        <version>${nexus-version}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>nexus-common</artifactId>
    <description>nexus 通用服务模块</description>
    <packaging>pom</packaging>

    <modules>
        <module>nexus-common-bom</module>
        <module>nexus-common-core</module>
        <module>nexus-common-doc</module>
        <module>nexus-common-easy-rules</module>
        <module>nexus-common-log</module>
        <module>nexus-common-mail</module>
        <module>nexus-common-mybatis-plus</module>
        <module>nexus-common-redis</module>
        <module>nexus-common-sensitive-word</module>
        <module>nexus-common-shiro</module>
        <module>nexus-common-token</module>
        <module>nexus-common-websocket</module>
        <module>nexus-common-excel</module>
        <module>nexus-common-oss</module>
        <module>nexus-common-netty</module>
    </modules>

</project>
